/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLServiceVybe.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLServiceVybe (0 custom class methods, 0 custom properties)

#import "GTLVybe.h"

@implementation GTLServiceVybe

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryVybe class],
                      [GTLVybeMediaGeoPtField class],
                      [GTLVybeMediaMediaListResponse class],
                      [GTLVybeMediaMediaQuery class],
                      [GTLVybeMediaMediaResponse class],
                      [GTLVybeMediaMediaUploadRequest class],
                      [GTLVybeMediaTribeCreateRequest class],
                      [GTLVybeMediaTribeResponse class],
                      [GTLVybeMediaTribesListResponse class],
                      [GTLVybeMediaUserResponse class],
                      [GTLVybeMediaUsersListResponse class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1.0";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://vybiest.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
