/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaMediaUploadRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaMediaUploadRequest (0 custom class methods, 5 custom properties)

#import "GTLVybeMediaMediaUploadRequest.h"

#import "GTLVybeMediaGeoPtField.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaMediaUploadRequest
//

@implementation GTLVybeMediaMediaUploadRequest
@dynamic blobKey, geotag, owner, timestamp, tribe;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"blob_key"
                                forKey:@"blobKey"];
  return map;
}

@end
