/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaGeoPtField.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaGeoPtField (0 custom class methods, 2 custom properties)

#import "GTLVybeMediaGeoPtField.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaGeoPtField
//

@implementation GTLVybeMediaGeoPtField
@dynamic latitude, longitude;
@end
