/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaUserResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaUserResponse (0 custom class methods, 3 custom properties)

#import "GTLVybeMediaUserResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaUserResponse
//

@implementation GTLVybeMediaUserResponse
@dynamic created, url, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"user_id"
                                forKey:@"userId"];
  return map;
}

@end
