/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaMediaQuery.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaMediaQuery (0 custom class methods, 4 custom properties)

#import "GTLVybeMediaMediaQuery.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaMediaQuery
//

@implementation GTLVybeMediaMediaQuery
@dynamic created, deviceId, url, username;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"device_id"
                                forKey:@"deviceId"];
  return map;
}

@end
