/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribesListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribesListResponse (0 custom class methods, 1 custom properties)

#import "GTLVybeMediaTribesListResponse.h"

#import "GTLVybeMediaTribeResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribesListResponse
//

@implementation GTLVybeMediaTribesListResponse
@dynamic tribes;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLVybeMediaTribeResponse class]
                                forKey:@"tribes"];
  return map;
}

@end
