/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribeResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribeResponse (0 custom class methods, 3 custom properties)

#import "GTLVybeMediaTribeResponse.h"

#import "GTLVybeMediaUserResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribeResponse
//

@implementation GTLVybeMediaTribeResponse
@dynamic members, name, tribeId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"tribe_id"
                                forKey:@"tribeId"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLVybeMediaUserResponse class]
                                forKey:@"members"];
  return map;
}

@end
