/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaMediaUploadRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaMediaUploadRequest (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVybeMediaGeoPtField;

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaMediaUploadRequest
//

@interface GTLVybeMediaMediaUploadRequest : GTLObject
@property (copy) NSString *blobKey;
@property (retain) GTLVybeMediaGeoPtField *geotag;
@property (copy) NSString *owner;
@property (retain) GTLDateTime *timestamp;
@property (copy) NSString *tribe;
@end
