/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribesListResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribesListResponse (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVybeMediaTribeResponse;

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribesListResponse
//

@interface GTLVybeMediaTribesListResponse : GTLObject
@property (retain) NSArray *tribes;  // of GTLVybeMediaTribeResponse
@end
