/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribeCreateRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribeCreateRequest (0 custom class methods, 3 custom properties)

#import "GTLVybeMediaTribeCreateRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribeCreateRequest
//

@implementation GTLVybeMediaTribeCreateRequest
@dynamic leader, name, publicProperty;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"public"
                                forKey:@"publicProperty"];
  return map;
}

@end
