/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribeCreateRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribeCreateRequest (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribeCreateRequest
//

@interface GTLVybeMediaTribeCreateRequest : GTLObject
@property (copy) NSString *leader;
@property (copy) NSString *name;

// Remapped to 'publicProperty' to avoid language reserved word 'public'.
@property (retain) NSNumber *publicProperty;  // boolValue

@end
