/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaMediaResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaMediaResponse (0 custom class methods, 3 custom properties)

#import "GTLVybeMediaMediaResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaMediaResponse
//

@implementation GTLVybeMediaMediaResponse
@dynamic blobKey, owner, timestamp;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"blob_key"
                                forKey:@"blobKey"];
  return map;
}

@end
