/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API

#import "GTLVybeConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeVybeUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
