/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaMediaListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaMediaListResponse (0 custom class methods, 1 custom properties)

#import "GTLVybeMediaMediaListResponse.h"

#import "GTLVybeMediaMediaResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaMediaListResponse
//

@implementation GTLVybeMediaMediaListResponse
@dynamic media;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLVybeMediaMediaResponse class]
                                forKey:@"media"];
  return map;
}

@end
