/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybe.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API

#import "GTLVybeConstants.h"

#import "GTLVybeMediaGeoPtField.h"
#import "GTLVybeMediaMediaListResponse.h"
#import "GTLVybeMediaMediaQuery.h"
#import "GTLVybeMediaMediaResponse.h"
#import "GTLVybeMediaMediaUploadRequest.h"
#import "GTLVybeMediaTribeCreateRequest.h"
#import "GTLVybeMediaTribeResponse.h"
#import "GTLVybeMediaTribesListResponse.h"
#import "GTLVybeMediaUserResponse.h"
#import "GTLVybeMediaUsersListResponse.h"

#import "GTLQueryVybe.h"
#import "GTLServiceVybe.h"
