/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaUsersListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaUsersListResponse (0 custom class methods, 1 custom properties)

#import "GTLVybeMediaUsersListResponse.h"

#import "GTLVybeMediaUserResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaUsersListResponse
//

@implementation GTLVybeMediaUsersListResponse
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLVybeMediaUserResponse class]
                                forKey:@"items"];
  return map;
}

@end
