/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLVybeMediaTribeResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   vybe/v1.0
// Description:
//   Media API
// Classes:
//   GTLVybeMediaTribeResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLVybeMediaUserResponse;

// ----------------------------------------------------------------------------
//
//   GTLVybeMediaTribeResponse
//

@interface GTLVybeMediaTribeResponse : GTLObject
@property (retain) NSArray *members;  // of GTLVybeMediaUserResponse
@property (copy) NSString *name;
@property (retain) NSNumber *tribeId;  // longLongValue
@end
